//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiLang.Translations {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MauiLang.Translations.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string CloseLabel {
            get {
                return ResourceManager.GetString("CloseLabel", resourceCulture);
            }
        }
        
        public static string EnterTextLabel {
            get {
                return ResourceManager.GetString("EnterTextLabel", resourceCulture);
            }
        }
        
        public static string ExplainLabel {
            get {
                return ResourceManager.GetString("ExplainLabel", resourceCulture);
            }
        }
        
        public static string GoBackLabel {
            get {
                return ResourceManager.GetString("GoBackLabel", resourceCulture);
            }
        }
        
        public static string LanguagesLabel {
            get {
                return ResourceManager.GetString("LanguagesLabel", resourceCulture);
            }
        }
        
        public static string NoExplainLabel {
            get {
                return ResourceManager.GetString("NoExplainLabel", resourceCulture);
            }
        }
        
        public static string OutputResponseLabel {
            get {
                return ResourceManager.GetString("OutputResponseLabel", resourceCulture);
            }
        }
        
        public static string OutputTextLabel {
            get {
                return ResourceManager.GetString("OutputTextLabel", resourceCulture);
            }
        }
        
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        public static string TranslationTargetLabel {
            get {
                return ResourceManager.GetString("TranslationTargetLabel", resourceCulture);
            }
        }
        
        public static string QuitLabel {
            get {
                return ResourceManager.GetString("QuitLabel", resourceCulture);
            }
        }
        
        public static string TranslateLabel {
            get {
                return ResourceManager.GetString("TranslateLabel", resourceCulture);
            }
        }
        
        public static string FavoriteLabel {
            get {
                return ResourceManager.GetString("FavoriteLabel", resourceCulture);
            }
        }
    }
}
